version: "3"
services:
  service_sample:
    build:
      context: ./
      dockerfile: Dockerfile
    image: service_sample
    ports:
      - "8080:8080"
  curl:
    image: appropriate/curl
    depends_on:
      - service_sample
    entrypoint: sh -c "sleep 3 && curl -XPOST service_sample:8080/product -d '{\"product\":\"Lacoste\"}'"